CD_OBJECTS     =
OBJECTS        = vdc_simple_sprite.o
ELF_TARGET     = vdc_simple_sprite.elf
BIN_TARGET     = vdc_simple_sprite.bin
ADD_FILES      = 
CDOUT          = vdc_simple_sprite_cd

include ../example.mk
