CD_OBJECTS     =
OBJECTS        = vdc_multi_sprite.o
ELF_TARGET     = vdc_multi_sprite.elf
BIN_TARGET     = vdc_multi_sprite.bin
ADD_FILES      = 
CDOUT          = vdc_multi_sprite_cd

include ../example.mk
