CD_OBJECTS     =
OBJECTS        = vdc_simple_background.o
ELF_TARGET     = vdc_simple_background.elf
BIN_TARGET     = vdc_simple_background.bin
ADD_FILES      = 
CDOUT          = vdc_simple_background_cd

include ../example.mk
